import type { Event } from "./types";
import { DEMO_ANCHOR_MS as T } from "./demoTime";
import { scoreToState } from "./stateUtils";

function seedEvent(p: Omit<Event, "state" | "momentumHistory"> & { momentumScore: number }): Event {
  const s = p.momentumScore;
  return {
    ...p,
    state: scoreToState(s),
    momentumHistory: [s, s, s, s, s, s, s, s],
  };
}

/** Original generic campus demo events (kept for reference or tooling). */
export const legacySeedEvents: Event[] = [
  seedEvent({
    id: "evt-basement",
    name: "Basement Show",
    category: "Music",
    host: "Campus Radio",
    locationName: "Arts Basement",
    x: 22,
    y: 68,
    distanceMinutes: 4,
    startTime: "8:00 PM",
    endTime: "11:00 PM",
    attendance: 28,
    baseAttendance: 24,
    watched: false,
    momentumScore: 24,
    trend: "flat",
    pulseCounts: { dead: 2, warming: 5, good: 1, packed: 0, crazy: 0 },
    pulseHistory: [
      { at: T - 120_000, label: "warming", source: "sim" },
      { at: T - 60_000, label: "dead", source: "sim" },
    ],
    recentActivity: [
      { at: T - 90_000, message: "Sound check wrapped — crowd thin" },
      { at: T - 45_000, message: "A few curious listeners drifted in" },
    ],
    lastAlertAt: null,
    isSurging: false,
    demoBias: 1.35,
  }),
  seedEvent({
    id: "evt-hacknight",
    name: "Hack Night",
    category: "Tech",
    host: "CS Guild",
    locationName: "Innovation Lab",
    x: 74,
    y: 32,
    distanceMinutes: 6,
    startTime: "7:30 PM",
    endTime: "12:00 AM",
    attendance: 52,
    baseAttendance: 48,
    watched: true,
    momentumScore: 46,
    trend: "rising",
    pulseCounts: { dead: 0, warming: 3, good: 8, packed: 2, crazy: 0 },
    pulseHistory: [
      { at: T - 80_000, label: "good", source: "sim" },
      { at: T - 30_000, label: "packed", source: "sim" },
    ],
    recentActivity: [
      { at: T - 70_000, message: "Demo table queue forming" },
      { at: T - 20_000, message: "Mentor dropped by with pizza intel" },
    ],
    lastAlertAt: T - 400_000,
    isSurging: false,
    demoBias: 1.2,
  }),
  seedEvent({
    id: "evt-food",
    name: "Food Pop-Up",
    category: "Food",
    host: "Night Market Club",
    locationName: "Quad Tent",
    x: 48,
    y: 48,
    distanceMinutes: 2,
    startTime: "6:00 PM",
    endTime: "10:00 PM",
    attendance: 96,
    baseAttendance: 90,
    watched: false,
    momentumScore: 62,
    trend: "rising",
    pulseCounts: { dead: 0, warming: 1, good: 6, packed: 12, crazy: 1 },
    pulseHistory: [{ at: T - 50_000, label: "packed", source: "sim" }],
    recentActivity: [{ at: T - 15_000, message: "Line stretching toward the fountain" }],
    lastAlertAt: null,
    isSurging: false,
    demoBias: 0.45,
  }),
  seedEvent({
    id: "evt-improv",
    name: "Improv Jam",
    category: "Theater",
    host: "Stage Collective",
    locationName: "Black Box",
    x: 33,
    y: 40,
    distanceMinutes: 8,
    startTime: "9:00 PM",
    endTime: "10:30 PM",
    attendance: 41,
    baseAttendance: 38,
    watched: false,
    momentumScore: 38,
    trend: "flat",
    pulseCounts: { dead: 1, warming: 7, good: 3, packed: 0, crazy: 0 },
    pulseHistory: [],
    recentActivity: [{ at: T - 60_000, message: "Warm-up games underway" }],
    lastAlertAt: null,
    isSurging: false,
    demoBias: 0.2,
  }),
  seedEvent({
    id: "evt-gallery",
    name: "Gallery Opening",
    category: "Art",
    host: "Fine Arts Dept",
    locationName: "North Gallery",
    x: 58,
    y: 72,
    distanceMinutes: 11,
    startTime: "5:30 PM",
    endTime: "8:30 PM",
    attendance: 19,
    baseAttendance: 22,
    watched: false,
    momentumScore: 16,
    trend: "falling",
    pulseCounts: { dead: 4, warming: 2, good: 0, packed: 0, crazy: 0 },
    pulseHistory: [],
    recentActivity: [{ at: T - 120_000, message: "Sparse crowd, wine still available" }],
    lastAlertAt: null,
    isSurging: false,
    demoBias: -0.4,
  }),
  seedEvent({
    id: "evt-film",
    name: "Indie Film Screening",
    category: "Film",
    host: "Cinema Society",
    locationName: "Lecture Hall B",
    x: 82,
    y: 58,
    distanceMinutes: 14,
    startTime: "7:00 PM",
    endTime: "9:30 PM",
    attendance: 63,
    baseAttendance: 60,
    watched: false,
    momentumScore: 44,
    trend: "flat",
    pulseCounts: { dead: 0, warming: 2, good: 9, packed: 1, crazy: 0 },
    pulseHistory: [],
    recentActivity: [{ at: T - 30_000, message: "Director Q&A announced" }],
    lastAlertAt: null,
    isSurging: false,
    demoBias: 0.1,
  }),
  seedEvent({
    id: "evt-dj",
    name: "DJ Set @ Quad",
    category: "Music",
    host: "Student Activities",
    locationName: "Main Quad",
    x: 50,
    y: 28,
    distanceMinutes: 3,
    startTime: "9:30 PM",
    endTime: "1:00 AM",
    attendance: 140,
    baseAttendance: 120,
    watched: true,
    momentumScore: 78,
    trend: "rising",
    pulseCounts: { dead: 0, warming: 0, good: 4, packed: 14, crazy: 6 },
    pulseHistory: [],
    recentActivity: [{ at: T - 10_000, message: "Bass you can feel in your chest" }],
    lastAlertAt: T - 200_000,
    isSurging: true,
    demoBias: 0.6,
  }),
  seedEvent({
    id: "evt-openmic",
    name: "Open Mic",
    category: "Music",
    host: "Coffee House",
    locationName: "Union Basement",
    x: 40,
    y: 82,
    distanceMinutes: 5,
    startTime: "8:30 PM",
    endTime: "11:00 PM",
    attendance: 34,
    baseAttendance: 32,
    watched: false,
    momentumScore: 31,
    trend: "rising",
    pulseCounts: { dead: 1, warming: 6, good: 2, packed: 0, crazy: 0 },
    pulseHistory: [],
    recentActivity: [{ at: T - 40_000, message: "First performer got a real laugh" }],
    lastAlertAt: null,
    isSurging: false,
    demoBias: 0.85,
  }),
  seedEvent({
    id: "evt-founders",
    name: "Founders Breakfast",
    category: "Startup",
    host: "Entrepreneurship Center",
    locationName: "Atrium",
    x: 66,
    y: 44,
    distanceMinutes: 9,
    startTime: "7:30 AM",
    endTime: "9:30 AM",
    attendance: 22,
    baseAttendance: 26,
    watched: false,
    momentumScore: 18,
    trend: "flat",
    pulseCounts: { dead: 3, warming: 4, good: 0, packed: 0, crazy: 0 },
    pulseHistory: [],
    recentActivity: [{ at: T - 180_000, message: "Coffee urns half full" }],
    lastAlertAt: null,
    isSurging: false,
    demoBias: -0.2,
  }),
  seedEvent({
    id: "evt-climb",
    name: "Climbing Social",
    category: "Sports",
    host: "Outdoor Club",
    locationName: "Rec Wall",
    x: 88,
    y: 38,
    distanceMinutes: 12,
    startTime: "6:30 PM",
    endTime: "9:00 PM",
    attendance: 47,
    baseAttendance: 45,
    watched: false,
    momentumScore: 42,
    trend: "flat",
    pulseCounts: { dead: 0, warming: 4, good: 7, packed: 0, crazy: 0 },
    pulseHistory: [],
    recentActivity: [{ at: T - 50_000, message: "New routes set — friendly belay partners" }],
    lastAlertAt: null,
    isSurging: false,
    demoBias: 0.15,
  }),
];

/**
 * MIT CPW–style real event titles and locations. Coordinates are spread across the
 * custom map canvas (west athletics / north makers / east Stata / central campus).
 * Strong demoBias on closing show, MITERS, fire show, and Roboteam for dramatic surges in sim.
 */
export const cpwSeedEvents: Event[] = [
  seedEvent({
    id: "cpw-asa-midway",
    name: "Association of Student Activities: ASA Midway",
    category: "showcase",
    host: "ASA",
    locationName: "Johnson Athletic Center (W34)",
    x: 16,
    y: 58,
    distanceMinutes: 7,
    startTime: "1:00 PM",
    endTime: "3:00 PM",
    attendance: 64,
    baseAttendance: 60,
    watched: false,
    momentumScore: 42,
    trend: "flat",
    pulseCounts: { dead: 0, warming: 4, good: 5, packed: 1, crazy: 0 },
    pulseHistory: [{ at: T - 55_000, label: "good", source: "sim" }],
    recentActivity: [{ at: T - 40_000, message: "Club tables filling in along the gym floor" }],
    lastAlertAt: null,
    isSurging: false,
    demoBias: 0.35,
  }),
  seedEvent({
    id: "cpw-ai-alignment",
    name: "MIT AI Alignment: Sandwiches & AI Risk",
    category: "tech",
    host: "MIT AI Alignment",
    locationName: "W20 Stratton Student Center, Outdoor Plaza",
    x: 46,
    y: 50,
    distanceMinutes: 5,
    startTime: "1:00 PM",
    endTime: "4:00 PM",
    attendance: 38,
    baseAttendance: 36,
    watched: false,
    momentumScore: 48,
    trend: "rising",
    pulseCounts: { dead: 0, warming: 3, good: 6, packed: 0, crazy: 0 },
    pulseHistory: [{ at: T - 48_000, label: "good", source: "sim" }],
    recentActivity: [{ at: T - 22_000, message: "Sandwich line and whiteboard debates in full swing" }],
    lastAlertAt: null,
    isSurging: false,
    demoBias: 0.55,
  }),
  seedEvent({
    id: "cpw-roboteam-boba",
    name: "MIT Roboteam: Bots, Boba and Board Games!",
    category: "robotics",
    host: "MIT Roboteam",
    locationName: "Campus location TBD",
    x: 52,
    y: 44,
    distanceMinutes: 6,
    startTime: "3:15 PM",
    endTime: "4:15 PM",
    attendance: 26,
    baseAttendance: 24,
    watched: false,
    momentumScore: 30,
    trend: "rising",
    pulseCounts: { dead: 1, warming: 6, good: 2, packed: 0, crazy: 0 },
    pulseHistory: [{ at: T - 35_000, label: "warming", source: "sim" }],
    recentActivity: [{ at: T - 18_000, message: "Mini bots on tables — boba cups stacking up" }],
    lastAlertAt: null,
    isSurging: false,
    demoBias: 1.48,
  }),
  seedEvent({
    id: "cpw-rocket-team",
    name: "MIT Rocket Team: Info Session + Lab Tour",
    category: "tech",
    host: "MIT Rocket Team",
    locationName: "Building 35, Room 225",
    x: 72,
    y: 48,
    distanceMinutes: 9,
    startTime: "3:30 PM",
    endTime: "5:00 PM",
    attendance: 44,
    baseAttendance: 42,
    watched: false,
    momentumScore: 52,
    trend: "flat",
    pulseCounts: { dead: 0, warming: 2, good: 8, packed: 1, crazy: 0 },
    pulseHistory: [],
    recentActivity: [{ at: T - 28_000, message: "Tour groups rotating through the bay" }],
    lastAlertAt: null,
    isSurging: false,
    demoBias: 0.4,
  }),
  seedEvent({
    id: "cpw-satellite-team",
    name: "MIT Satellite Team: Food & Telemetry",
    category: "tech",
    host: "MIT Satellite Team",
    locationName: "33-116 Guggenheim Laboratory",
    x: 68,
    y: 62,
    distanceMinutes: 10,
    startTime: "4:00 PM",
    endTime: "5:00 PM",
    attendance: 31,
    baseAttendance: 30,
    watched: false,
    momentumScore: 44,
    trend: "rising",
    pulseCounts: { dead: 0, warming: 4, good: 5, packed: 0, crazy: 0 },
    pulseHistory: [],
    recentActivity: [{ at: T - 25_000, message: "Telemetry plots on screen — snacks on the side" }],
    lastAlertAt: null,
    isSurging: false,
    demoBias: 0.3,
  }),
  seedEvent({
    id: "cpw-arcturus-underwater",
    name: "Arcturus Robotics: Underwater Battlebots",
    category: "robotics",
    host: "Arcturus Robotics",
    locationName: "NW98-151 MIT Sea Grant",
    x: 12,
    y: 28,
    distanceMinutes: 14,
    startTime: "4:00 PM",
    endTime: "6:00 PM",
    attendance: 22,
    baseAttendance: 24,
    watched: false,
    momentumScore: 18,
    trend: "falling",
    pulseCounts: { dead: 3, warming: 3, good: 1, packed: 0, crazy: 0 },
    pulseHistory: [],
    recentActivity: [{ at: T - 60_000, message: "Tank tests on delay — small crowd watching" }],
    lastAlertAt: null,
    isSurging: false,
    demoBias: -0.15,
  }),
  seedEvent({
    id: "cpw-closing-show",
    name: "CPW Closing Show",
    category: "performance",
    host: "CPW Committee",
    locationName: "W16 Kresge Auditorium",
    x: 28,
    y: 38,
    distanceMinutes: 4,
    startTime: "6:00 PM",
    endTime: "7:30 PM",
    attendance: 55,
    baseAttendance: 50,
    watched: false,
    momentumScore: 34,
    trend: "rising",
    pulseCounts: { dead: 0, warming: 8, good: 2, packed: 0, crazy: 0 },
    pulseHistory: [{ at: T - 42_000, label: "warming", source: "sim" }],
    recentActivity: [{ at: T - 15_000, message: "House lights dim — preshow murmur building" }],
    lastAlertAt: null,
    isSurging: false,
    demoBias: 1.58,
  }),
  seedEvent({
    id: "cpw-firstxmit",
    name: "FIRSTxMIT: Meet & Greet (SECOND Robotics Competition)",
    category: "social",
    host: "FIRSTxMIT",
    locationName: "10-105 Bush Room",
    x: 58,
    y: 54,
    distanceMinutes: 8,
    startTime: "8:00 PM",
    endTime: "10:00 PM",
    attendance: 48,
    baseAttendance: 46,
    watched: false,
    momentumScore: 46,
    trend: "flat",
    pulseCounts: { dead: 0, warming: 3, good: 7, packed: 1, crazy: 0 },
    pulseHistory: [],
    recentActivity: [{ at: T - 20_000, message: "Rookies trading team stories by the podium" }],
    lastAlertAt: null,
    isSurging: false,
    demoBias: 0.45,
  }),
  seedEvent({
    id: "cpw-spinning-fire",
    name: "MIT Spinning Arts: Fire Show",
    category: "performance",
    host: "MIT Spinning Arts",
    locationName: "Stata Center (32), Ray and Maria Stata Amphitheater",
    x: 84,
    y: 36,
    distanceMinutes: 11,
    startTime: "8:00 PM",
    endTime: "10:00 PM",
    attendance: 72,
    baseAttendance: 68,
    watched: false,
    momentumScore: 38,
    trend: "rising",
    pulseCounts: { dead: 0, warming: 7, good: 3, packed: 0, crazy: 0 },
    pulseHistory: [{ at: T - 30_000, label: "warming", source: "sim" }],
    recentActivity: [{ at: T - 12_000, message: "Safety perimeter set — crowd packing the amphitheater steps" }],
    lastAlertAt: null,
    isSurging: false,
    demoBias: 1.55,
  }),
  seedEvent({
    id: "cpw-miters-build-night",
    name: "MITERS: Hackerspace Tour + Build Night + Tesla Coil",
    category: "makers",
    host: "MITERS",
    locationName: "N52-115 MITERS",
    x: 38,
    y: 22,
    distanceMinutes: 13,
    startTime: "7:30 PM",
    endTime: "1:00 AM",
    attendance: 41,
    baseAttendance: 38,
    watched: false,
    momentumScore: 28,
    trend: "rising",
    pulseCounts: { dead: 1, warming: 7, good: 2, packed: 0, crazy: 0 },
    pulseHistory: [{ at: T - 50_000, label: "warming", source: "sim" }],
    recentActivity: [{ at: T - 16_000, message: "Tour loops ending — workbenches warming up for the late crew" }],
    lastAlertAt: null,
    isSurging: false,
    demoBias: 1.62,
  }),
];

/** Active dataset for the app: MIT CPW events. */
export const SEED_EVENTS: Event[] = cpwSeedEvents;

export function cloneSeedEvents(): Event[] {
  return SEED_EVENTS.map((e) => structuredClone(e));
}
